//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bandwidth) DeepCopyInto(out *Bandwidth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bandwidth.
func (in *Bandwidth) DeepCopy() *Bandwidth {
	if in == nil {
		return nil
	}
	out := new(Bandwidth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Bandwidth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthDefinition) DeepCopyInto(out *BandwidthDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthDefinition.
func (in *BandwidthDefinition) DeepCopy() *BandwidthDefinition {
	if in == nil {
		return nil
	}
	out := new(BandwidthDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthList) DeepCopyInto(out *BandwidthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bandwidth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthList.
func (in *BandwidthList) DeepCopy() *BandwidthList {
	if in == nil {
		return nil
	}
	out := new(BandwidthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BandwidthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthRequest) DeepCopyInto(out *BandwidthRequest) {
	*out = *in
	out.Bandwidth = in.Bandwidth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthRequest.
func (in *BandwidthRequest) DeepCopy() *BandwidthRequest {
	if in == nil {
		return nil
	}
	out := new(BandwidthRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthSpec) DeepCopyInto(out *BandwidthSpec) {
	*out = *in
	out.Capacity = in.Capacity
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make([]BandwidthRequest, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthSpec.
func (in *BandwidthSpec) DeepCopy() *BandwidthSpec {
	if in == nil {
		return nil
	}
	out := new(BandwidthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthStatus) DeepCopyInto(out *BandwidthStatus) {
	*out = *in
	out.Used = in.Used
	out.Remaining = in.Remaining
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make([]ReservationInfo, len(*in))
		copy(*out, *in)
	}
	out.Capacity = in.Capacity
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthStatus.
func (in *BandwidthStatus) DeepCopy() *BandwidthStatus {
	if in == nil {
		return nil
	}
	out := new(BandwidthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Capacity) DeepCopyInto(out *Capacity) {
	*out = *in
	out.Local = in.Local
	out.Network = in.Network
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Capacity.
func (in *Capacity) DeepCopy() *Capacity {
	if in == nil {
		return nil
	}
	out := new(Capacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationInfo) DeepCopyInto(out *ReservationInfo) {
	*out = *in
	out.Bandwidth = in.Bandwidth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationInfo.
func (in *ReservationInfo) DeepCopy() *ReservationInfo {
	if in == nil {
		return nil
	}
	out := new(ReservationInfo)
	in.DeepCopyInto(out)
	return out
}
